import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Descomplica Auto",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="pt-br">
      <body className="bg-[#FBF2E7]">
        {children}
      </body>
    </html>
  );
}
